version: "3"

networks:
  web:
    external: true

services:
  evokegen-app:
    image: evokegen:latest
    depends_on:
      - evokegen-db
    networks:
      - web

  evokegen-db:
    image: postgres:latest
    networks:
      - web
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=evokegen
      - POSTGRES_PASSWORD=rcZHiYtysbu8DIZpRGhvb0Te4yChM
      - POSTGRES_DB=evokegen

  nginx-proxy-manager:
    image: "jc21/nginx-proxy-manager:2.9.22"
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - web
